package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Artisans generated by hbm2java
 */
public class Artisans  implements java.io.Serializable {


     private String idArtisan;
     private String nomArtisan;
     private String telephone;
     private String adresse;
     private Set produitses = new HashSet(0);

    public Artisans() {
    }

	
    public Artisans(String idArtisan, String adresse) {
        this.idArtisan = idArtisan;
        this.adresse = adresse;
    }
    public Artisans(String idArtisan, String nomArtisan, String telephone, String adresse, Set produitses) {
       this.idArtisan = idArtisan;
       this.nomArtisan = nomArtisan;
       this.telephone = telephone;
       this.adresse = adresse;
       this.produitses = produitses;
    }
   
    public String getIdArtisan() {
        return this.idArtisan;
    }
    
    public void setIdArtisan(String idArtisan) {
        this.idArtisan = idArtisan;
    }
    public String getNomArtisan() {
        return this.nomArtisan;
    }
    
    public void setNomArtisan(String nomArtisan) {
        this.nomArtisan = nomArtisan;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }




}


