package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1



/**
 * Factures generated by hbm2java
 */
public class Factures  implements java.io.Serializable {


     private String codeFacture;
     private Commandes commandes;

    public Factures() {
    }

    public Factures(String codeFacture, Commandes commandes) {
       this.codeFacture = codeFacture;
       this.commandes = commandes;
    }
   
    public String getCodeFacture() {
        return this.codeFacture;
    }
    
    public void setCodeFacture(String codeFacture) {
        this.codeFacture = codeFacture;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }




}


