package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1



/**
 * IngredientsLangues generated by hbm2java
 */
public class IngredientsLangues  implements java.io.Serializable {


     private IngredientsLanguesId id;
     private Ingredients ingredients;
     private Langues langues;
     private String nomIngredients;

    public IngredientsLangues() {
    }

    public IngredientsLangues(IngredientsLanguesId id, Ingredients ingredients, Langues langues, String nomIngredient) {
       this.id = id;
       this.ingredients = ingredients;
       this.langues = langues;
       this.nomIngredients = nomIngredient;
    }
   
    public IngredientsLanguesId getId() {
        return this.id;
    }
    
    public void setId(IngredientsLanguesId _id) {
        this.id = _id;
    }
    public Ingredients getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Ingredients _ingredients) {
        this.ingredients = _ingredients;
    }
    public Langues getLangues() {
        return this.langues;
    }
    
    public void setLangues(Langues _langues) {
        this.langues = _langues;
    }
    public String getNomIngredients() {
        return this.nomIngredients;
    }
    
    public void setNomIngredients(String _nomIngredient) {
        this.nomIngredients = _nomIngredient;
    }




}


