package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ingredients generated by hbm2java
 */
public class Ingredients  implements java.io.Serializable {


     private String idIngredient;
     private Set produitses = new HashSet(0);
     private Set ingredientsLangueses = new HashSet(0);
     private String nomIngredient;

   
    public Ingredients() {
    }

	
    public Ingredients(String idIngredient) {
        this.idIngredient = idIngredient;
    }
    public Ingredients(String idIngredient, Set produitses, Set ingredientsLangueses) {
       this.idIngredient = idIngredient;
       this.produitses = produitses;
       this.ingredientsLangueses = ingredientsLangueses;
    }
   
    public String getIdIngredient() {
        return this.idIngredient;
    }
    
    public void setIdIngredient(String idIngredient) {
        this.idIngredient = idIngredient;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }
    public Set getIngredientsLangueses() {
        return this.ingredientsLangueses;
    }
    
    public void setIngredientsLangueses(Set ingredientsLangueses) {
        this.ingredientsLangueses = ingredientsLangueses;
    }

 public String getNomIngredient() {
        return nomIngredient;
    }

    public void setNomIngredient(String nomIngredient) {
        this.nomIngredient = nomIngredient;
    }


}


