package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Langues generated by hbm2java
 */
public class Langues  implements java.io.Serializable {


     private String codeLangue;
     private String nomLangue;
     private Set produitsLangueses = new HashSet(0);
     private Set ingredientsLangueses = new HashSet(0);

    public Langues() {
    }

	
    public Langues(String codeLangue) {
        this.codeLangue = codeLangue;
    }
    public Langues(String codeLangue, String nomLangue, Set produitsLangueses, Set ingredientsLangueses) {
       this.codeLangue = codeLangue;
       this.nomLangue = nomLangue;
       this.produitsLangueses = produitsLangueses;
       this.ingredientsLangueses = ingredientsLangueses;
    }
   
    public String getCodeLangue() {
        return this.codeLangue;
    }
    
    public void setCodeLangue(String codeLangue) {
        this.codeLangue = codeLangue;
    }
    public String getNomLangue() {
        return this.nomLangue;
    }
    
    public void setNomLangue(String nomLangue) {
        this.nomLangue = nomLangue;
    }
    public Set getProduitsLangueses() {
        return this.produitsLangueses;
    }
    
    public void setProduitsLangueses(Set produitsLangueses) {
        this.produitsLangueses = produitsLangueses;
    }
    public Set getIngredientsLangueses() {
        return this.ingredientsLangueses;
    }
    
    public void setIngredientsLangueses(Set ingredientsLangueses) {
        this.ingredientsLangueses = ingredientsLangueses;
    }




}


