package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1



/**
 * LignesCommandeId generated by hbm2java
 */
public class LignesCommandeId  implements java.io.Serializable {


     private String codeProduit;
     private String idCommande;

    public LignesCommandeId() {
    }

    public LignesCommandeId(String codeProduit, String idCommande) {
       this.codeProduit = codeProduit;
       this.idCommande = idCommande;
    }
   
    public String getCodeProduit() {
        return this.codeProduit;
    }
    
    public void setCodeProduit(String codeProduit) {
        this.codeProduit = codeProduit;
    }
    public String getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(String idCommande) {
        this.idCommande = idCommande;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LignesCommandeId) ) return false;
		 LignesCommandeId castOther = ( LignesCommandeId ) other; 
         
		 return ( (this.getCodeProduit()==castOther.getCodeProduit()) || ( this.getCodeProduit()!=null && castOther.getCodeProduit()!=null && this.getCodeProduit().equals(castOther.getCodeProduit()) ) )
 && ( (this.getIdCommande()==castOther.getIdCommande()) || ( this.getIdCommande()!=null && castOther.getIdCommande()!=null && this.getIdCommande().equals(castOther.getIdCommande()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeProduit() == null ? 0 : this.getCodeProduit().hashCode() );
         result = 37 * result + ( getIdCommande() == null ? 0 : this.getIdCommande().hashCode() );
         return result;
   }   


}


