package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1



/**
 * ProduitsLanguesId generated by hbm2java
 */
public class ProduitsLanguesId  implements java.io.Serializable {


     private String codeProduit;
     private String codeLangue;

    public ProduitsLanguesId() {
    }

    public ProduitsLanguesId(String codeProduit, String codeLangue) {
       this.codeProduit = codeProduit;
       this.codeLangue = codeLangue;
    }
   
    public String getCodeProduit() {
        return this.codeProduit;
    }
    
    public void setCodeProduit(String codeProduit) {
        this.codeProduit = codeProduit;
    }
    public String getCodeLangue() {
        return this.codeLangue;
    }
    
    public void setCodeLangue(String codeLangue) {
        this.codeLangue = codeLangue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProduitsLanguesId) ) return false;
		 ProduitsLanguesId castOther = ( ProduitsLanguesId ) other; 
         
		 return ( (this.getCodeProduit()==castOther.getCodeProduit()) || ( this.getCodeProduit()!=null && castOther.getCodeProduit()!=null && this.getCodeProduit().equals(castOther.getCodeProduit()) ) )
 && ( (this.getCodeLangue()==castOther.getCodeLangue()) || ( this.getCodeLangue()!=null && castOther.getCodeLangue()!=null && this.getCodeLangue().equals(castOther.getCodeLangue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeProduit() == null ? 0 : this.getCodeProduit().hashCode() );
         result = 37 * result + ( getCodeLangue() == null ? 0 : this.getCodeLangue().hashCode() );
         return result;
   }   


}


