package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Produits generated by hbm2java
 */
public class Produits  implements java.io.Serializable {

private String name;
    private String description;

    
     private String codeProduit;
     private Artisans artisans;
     private short qtyProduit;
     private BigDecimal prixProduit;
     private String photoProduit;
     private Set produitsLangueses = new HashSet(0);
     private Set ingredientses = new HashSet(0);
     private Set lignesCommandes = new HashSet(0);

    public Produits() {
    }

	
    public Produits(String codeProduit, Artisans artisans, short qtyProduit, String photoProduit) {
        this.codeProduit = codeProduit;
        this.artisans = artisans;
        this.qtyProduit = qtyProduit;
        this.photoProduit = photoProduit;
    }
    public Produits(String codeProduit, Artisans artisans, short qtyProduit, BigDecimal prixProduit, String photoProduit, Set produitsLangueses, Set ingredientses, Set lignesCommandes) {
       this.codeProduit = codeProduit;
       this.artisans = artisans;
       this.qtyProduit = qtyProduit;
       this.prixProduit = prixProduit;
       this.photoProduit = photoProduit;
       this.produitsLangueses = produitsLangueses;
       this.ingredientses = ingredientses;
       this.lignesCommandes = lignesCommandes;
    }
   public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    public String getCodeProduit() {
        return this.codeProduit;
    }
    
    public void setCodeProduit(String codeProduit) {
        this.codeProduit = codeProduit;
    }
    public Artisans getArtisans() {
        return this.artisans;
    }
    
    public void setArtisans(Artisans artisans) {
        this.artisans = artisans;
    }
    public short getQtyProduit() {
        return this.qtyProduit;
    }
    
    public void setQtyProduit(short qtyProduit) {
        this.qtyProduit = qtyProduit;
    }
    public BigDecimal getPrixProduit() {
        return this.prixProduit;
    }
    
    public void setPrixProduit(BigDecimal prixProduit) {
        this.prixProduit = prixProduit;
    }
    public String getPhotoProduit() {
        return this.photoProduit;
    }
    
    public void setPhotoProduit(String photoProduit) {
        this.photoProduit = photoProduit;
    }
    public Set getProduitsLangueses() {
        return this.produitsLangueses;
    }
    
    public void setProduitsLangueses(Set produitsLangueses) {
        this.produitsLangueses = produitsLangueses;
    }
    public Set getIngredientses() {
        return this.ingredientses;
    }
    
    public void setIngredientses(Set ingredientses) {
        this.ingredientses = ingredientses;
    }
    public Set getLignesCommandes() {
        return this.lignesCommandes;
    }
    
    public void setLignesCommandes(Set lignesCommandes) {
        this.lignesCommandes = lignesCommandes;
    }




}


