package Modele;
// Generated Sep 12, 2018 9:59:37 AM by Hibernate Tools 4.3.1



/**
 * ProduitsLangues generated by hbm2java
 */
public class ProduitsLangues  implements java.io.Serializable {


     private ProduitsLanguesId id;
     private Langues langues;
     private Produits produits;
     private String nomProduit;
     private String description;

    public ProduitsLangues() {
    }

    public ProduitsLangues(ProduitsLanguesId id, Langues langues, Produits produits, String nomProduit, String description) {
       this.id = id;
       this.langues = langues;
       this.produits = produits;
       this.nomProduit = nomProduit;
       this.description = description;
    }
   
    public ProduitsLanguesId getId() {
        return this.id;
    }
    
    public void setId(ProduitsLanguesId id) {
        this.id = id;
    }
    public Langues getLangues() {
        return this.langues;
    }
    
    public void setLangues(Langues langues) {
        this.langues = langues;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public String getNomProduit() {
        return this.nomProduit;
    }
    
    public void setNomProduit(String nomProduit) {
        this.nomProduit = nomProduit;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


